module.exports = {
  "ALIVE_IMG": "https://files.catbox.moe/8kxui5.jpg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "private",
  "BOT_NUMBER": "237696262128",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": true,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "YOUSSOUF YK",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false
};
